// FLASH_SALES
import gameHandImg from "@/assets/images/products/gamepad.png";
import keyboardImg from "@/assets/images/products/keyboard.png";
import monitorImg from "@/assets/images/products/monitor.png";
import chairImg from "@/assets/images/products/chair.png";
// BEST_SELLERS
import Coat from "@/assets/images/products/coat.png";
import DuffleBag from "@/assets/images/products/bag.png";
import LiquidCooler from "@/assets/images/products/cooler.png";
import BookSelf from "@/assets/images/products/book-self.png";
// EXPLORE
import dogFoodImg from "@/assets/images/products/dog-food-variety.png";
import cameraImg from "@/assets/images/products/canon-dslr-camera.png";
import laptopImg from "@/assets/images/products/asus-gaming-laptop.png";
import skincareImg from "@/assets/images/products/curology-skincare.png";
import electricCarImg from "@/assets/images/products/kids-electric-car.png";
import soccerCleatsImg from "@/assets/images/products/soccer-cleats.png";
import gamepadImg from "@/assets/images/products/usb-gamepad.png";
import jacketImg from "@/assets/images/products/satin-jacket.png";

export const FLASH_SALES = [
  {
    id: 1,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    originalPrice: 160,
    discount: 40,
    rating: 4.5,
    reviews: 88,
    image: gameHandImg,
    // isNew: false,
  },
  {
    id: 2,
    name: "AK-900 Wired Keyboard",
    price: 960,
    originalPrice: 1160,
    discount: 35,
    rating: 4,
    reviews: 75,
    image: keyboardImg,
  },
  {
    id: 3,
    name: "IPS LCD Gaming Monitor",
    price: 370,
    originalPrice: 400,
    discount: 30,
    rating: 5,
    reviews: 99,
    image: monitorImg,
  },
  {
    id: 4,
    name: "S-Series Comfort Chair",
    price: 375,
    originalPrice: 400,
    discount: 25,
    rating: 4.5,
    reviews: 99,
    image: chairImg,
  },
  {
    id: 5,
    name: "Gaming Headset Pro",
    price: 89,
    originalPrice: 120,
    discount: 26,
    rating: 4.3,
    reviews: 156,
    image: gameHandImg,
  },
  {
    id: 6,
    name: "RGB Gaming Mouse",
    price: 45,
    originalPrice: 60,
    discount: 25,
    rating: 4.7,
    reviews: 203,
    image: keyboardImg,
  },
  {
    id: 7,
    name: "Mechanical Keyboard Pro",
    price: 189,
    originalPrice: 250,
    discount: 24,
    rating: 4.8,
    reviews: 145,
    image: monitorImg,
  },
  {
    id: 8,
    name: "4K Webcam Ultra",
    price: 299,
    originalPrice: 399,
    discount: 25,
    rating: 4.6,
    reviews: 89,
    image: chairImg,
  },
  {
    id: 9,
    name: "Gaming Laptop Stand",
    price: 79,
    originalPrice: 99,
    discount: 20,
    rating: 4.4,
    reviews: 234,
    image: gameHandImg,
  },
];
export const BEST_SELLERS = [
  {
    id: 1,
    name: "The north coat",
    price: 120,
    originalPrice: 160,
    discount: null,
    rating: 4.5,
    reviews: 88,
    image: Coat,
    isNew: null,
  },
  {
    id: 2,
    name: "Gucci duffle bag",
    price: 960,
    originalPrice: 1160,
    discount: null,
    rating: 4,
    reviews: 75,
    image: DuffleBag,
    isNew: null,
  },
  {
    id: 3,
    name: "RGB liquid CPU Cooler",
    price: 370,
    originalPrice: 400,
    discount: null,
    rating: 5,
    reviews: 99,
    image: LiquidCooler,
    isNew: null,
  },
  {
    id: 4,
    name: "Small BookSelf",
    price: 375,
    originalPrice: 400,
    discount: null,
    rating: 4.5,
    reviews: 99,
    image: BookSelf,
    isNew: null,
  },
];

export const EXPLORE = [
  {
    id: 1,
    name: "Breed Dry Dog Food",
    price: 100,
    rating: 3,
    reviews: 35,
    image: dogFoodImg,
    discount:null,
    isNew: null
  },
  {
    id: 2,
    name: "CANON EOS DSLR Camera",
    price: 360,
    rating: 4,
    reviews: 95,
    image: cameraImg,
    discount:null,
    isNew: null
  },
  {
    id: 3,
    name: "ASUS FHD Gaming Laptop",
    price: 700,
    rating: 5,
    reviews: 325,
    image: laptopImg,
    discount:null,
    isNew: null
  },
  {
    id: 4,
    name: "Curology Product Set",
    price: 500,
    rating: 4,
    reviews: 145,
    image: skincareImg,
    discount:null,
    isNew: null
  },
  {
    id: 5,
    name: "Kids Electric Car",
    price: 960,
    rating: 5,
    reviews: 65,
    image: electricCarImg,
    isNew: true,
    discount:null,
  },
  {
    id: 6,
    name: "Jr. Zoom Soccer Cleats",
    price: 1160,
    rating: 5,
    reviews: 35,
    image: soccerCleatsImg,
    discount:null,
    isNew: null
  },
  {
    id: 7,
    name: "GP11 Shooter USB Gamepad",
    price: 660,
    rating: 4.5,
    reviews: 55,
    image: gamepadImg,
    isNew: false,
    discount:null,
    
  },
  {
    id: 8,
    name: "Quilted Satin Jacket",
    price: 660,
    rating: 4.5,
    reviews: 55,
    image: jacketImg,
    isNew: false,
    discount:null,
  },
];

export const PRODUCTS = [
  {
    id: 1,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    originalPrice: 160,
    discount: 40,
    rating: 4.5,
    reviews: 88,
    image: gameHandImg,
    // isNew: false,
  },
  {
    id: 2,
    name: "AK-900 Wired Keyboard",
    price: 960,
    originalPrice: 1160,
    discount: 35,
    rating: 4,
    reviews: 75,
    image: keyboardImg,
  },
  {
    id: 3,
    name: "IPS LCD Gaming Monitor",
    price: 370,
    originalPrice: 400,
    discount: 30,
    rating: 5,
    reviews: 99,
    image: monitorImg,
  },
  {
    id: 4,
    name: "S-Series Comfort Chair",
    price: 375,
    originalPrice: 400,
    discount: 25,
    rating: 4.5,
    reviews: 99,
    image: chairImg,
  },
  {
    id: 5,
    name: "Gaming Headset Pro",
    price: 89,
    originalPrice: 120,
    discount: 26,
    rating: 4.3,
    reviews: 156,
    image: gameHandImg,
  },
  {
    id: 6,
    name: "RGB Gaming Mouse",
    price: 45,
    originalPrice: 60,
    discount: 25,
    rating: 4.7,
    reviews: 203,
    image: keyboardImg,
  },
  {
    id: 7,
    name: "Mechanical Keyboard Pro",
    price: 189,
    originalPrice: 250,
    discount: 24,
    rating: 4.8,
    reviews: 145,
    image: monitorImg,
  },
  {
    id: 8,
    name: "4K Webcam Ultra",
    price: 299,
    originalPrice: 399,
    discount: 25,
    rating: 4.6,
    reviews: 89,
    image: chairImg,
  },
  {
    id: 9,
    name: "Gaming Laptop Stand",
    price: 79,
    originalPrice: 99,
    discount: 20,
    rating: 4.4,
    reviews: 234,
    image: gameHandImg,
  },
];
