export const PRODUCTS = [
    {
      id: 1,
      name: "HAVIT HV-G92 Gamepad",
      price: 120,
      originalPrice: 160,
      discount: 40,
      rating: 4.5,
      reviews: 88,
      image: "../../../assets/images/products/gamepad.png",
      // isNew: false,
    },
    {
      id: 2,
      name: "AK-900 Wired Keyboard",
      price: 960,
      originalPrice: 1160,
      discount: 35,
      rating: 4,
      reviews: 75,
      image: "/mechanical-keyboard.png",
    },
    {
      id: 3,
      name: "IPS LCD Gaming Monitor",
      price: 370,
      originalPrice: 400,
      discount: 30,
      rating: 5,
      reviews: 99,
      image: "/gaming-monitor-setup.png",
    },
    {
      id: 4,
      name: "S-Series Comfort Chair",
      price: 375,
      originalPrice: 400,
      discount: 25,
      rating: 4.5,
      reviews: 99,
      image: "/ergonomic-gaming-chair.png",
    },
    {
      id: 5,
      name: "Gaming Headset Pro",
      price: 89,
      originalPrice: 120,
      discount: 26,
      rating: 4.3,
      reviews: 156,
      image: "/gaming-headset.png",
    },
    {
      id: 6,
      name: "RGB Gaming Mouse",
      price: 45,
      originalPrice: 60,
      discount: 25,
      rating: 4.7,
      reviews: 203,
      image: "/gaming-mouse.png",
    },
    {
      id: 7,
      name: "Mechanical Keyboard Pro",
      price: 189,
      originalPrice: 250,
      discount: 24,
      rating: 4.8,
      reviews: 145,
      image: "/pro-keyboard.png",
    },
    {
      id: 8,
      name: "4K Webcam Ultra",
      price: 299,
      originalPrice: 399,
      discount: 25,
      rating: 4.6,
      reviews: 89,
      image: "/webcam-4k.png",
    },
    {
      id: 9,
      name: "Gaming Laptop Stand",
      price: 79,
      originalPrice: 99,
      discount: 20,
      rating: 4.4,
      reviews: 234,
      image: "/laptop-stand.png",
    },
  ];

